#! /bin/sh

NAME=contaserver
DESC="Server dei contatori"
LOGFILE="/var/log/${NAME}.log"
LOCKFILE="/var/run/${NAME}.lock"
EXE="/usr/bin/local/contaserver.exe"

# Percorso del demonizzatore mono
DAEMON="/usr/bin/mono-service"

test -x $DAEMON || exit 0

set -e

case "$1" in
start)
echo -n "Starting ${DESC}: "
$DAEMON $EXE -l:$LOCKFILE --debug >> $LOGFILE 2>> $LOGFILE &
echo "$NAME."
;;
stop)
echo -n "Stopping $DESC: "
kill -9 `cat $LOCKFILE`
echo "$NAME."
rm -f $LOCKFILE
;;
restart|force-reload)
echo -n "Restarting $DESC: "
kill -9 `cat $LOCKFILE`
rm -f $LOCKFILE
sleep 1
$DAEMON $EXE -l:$LOCKFILE --debug >> $LOGFILE 2>> $LOGFILE &
echo "$NAME."
;;
*)
N=/etc/init.d/$NAME
echo "Usage: $N {start|stop|restart|force-reload}" >&2
exit 1
;;
esac

exit 0
