#! /bin/sh

NAME=contaserver
DESC="Server dei contatori"
LOGFILE="/var/log/${NAME}.log"
LOCKFILE="/var/run/${NAME}.lock"
EXE="/usr/bin/local/contaserver.exr"

# Percorso del demonizzatore mono
DAEMON="/usr/bin/mono-service"

test -x $DAEMON || exit 0

set -e

case "$1" in
start)
echo -n "Starting ${DESC}: "
/usr/bin/mono-service /usr/bin/local/contaserver.exe -l:/var/run/contaserver.lock --debug >> /var/log/contaserver.log 2>> /var/log/contaserver.log &
echo "$NAME."
;;
stop)
echo -n "Stopping $DESC: "
kill -9 `cat /var/run/contaserver.lock`
echo "$NAME."
rm -f /var/run/contaserver.lock
;;
restart|force-reload)
echo -n "Restarting $DESC: "
kill -9 `cat /var/run/contaserver.lock`
rm -f /var/run/contaserver.lock
sleep 1
/usr/bin/mono-service /usr/bin/local/contaserver.exe -l:/var/run/contaserver.lock --debug >> /var/log/contaserver.log 2>> /var/log/contaserver.log &
echo "$NAME."
;;
*)
N=/etc/init.d/$NAME
echo "Usage: $N {start|stop|restart|force-reload}" >&2
exit 1
;;
esac

exit 0
